/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kalkulator_sederhana;

/**
 *
 * @author User
 */
public class kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form kalkulator
     */
    String angka;
    double jumlah,angka1,angka2;
    int pilih;
    public kalkulator() {
        initComponents();
         angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bttn2 = new javax.swing.JButton();
        Bttn3 = new javax.swing.JButton();
        bttn0 = new javax.swing.JButton();
        bttnKoma = new javax.swing.JButton();
        Bttn7 = new javax.swing.JButton();
        bttnKali = new javax.swing.JButton();
        Bttn8 = new javax.swing.JButton();
        bttnKurang = new javax.swing.JButton();
        Bttn9 = new javax.swing.JButton();
        bttnTambah = new javax.swing.JButton();
        bttn4 = new javax.swing.JButton();
        bttnSamadengan = new javax.swing.JButton();
        Bttn1 = new javax.swing.JButton();
        bttnClear = new javax.swing.JButton();
        Bttn5 = new javax.swing.JButton();
        bttnBagi = new javax.swing.JButton();
        Bttn6 = new javax.swing.JButton();
        TampilHasil = new javax.swing.JTextField();
        modulus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bttn2.setText("2");
        Bttn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn2ActionPerformed(evt);
            }
        });

        Bttn3.setText("3");
        Bttn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn3ActionPerformed(evt);
            }
        });

        bttn0.setText("0");
        bttn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn0ActionPerformed(evt);
            }
        });

        bttnKoma.setText(",");
        bttnKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnKomaActionPerformed(evt);
            }
        });

        Bttn7.setText("7");
        Bttn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn7ActionPerformed(evt);
            }
        });

        bttnKali.setText("x");
        bttnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnKaliActionPerformed(evt);
            }
        });

        Bttn8.setText("8");
        Bttn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn8ActionPerformed(evt);
            }
        });

        bttnKurang.setText("-");
        bttnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnKurangActionPerformed(evt);
            }
        });

        Bttn9.setText("9");
        Bttn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn9ActionPerformed(evt);
            }
        });

        bttnTambah.setText("+");
        bttnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnTambahActionPerformed(evt);
            }
        });

        bttn4.setText("4");
        bttn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn4ActionPerformed(evt);
            }
        });

        bttnSamadengan.setText("=");
        bttnSamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSamadenganActionPerformed(evt);
            }
        });

        Bttn1.setText("1");
        Bttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn1ActionPerformed(evt);
            }
        });

        bttnClear.setText("C");
        bttnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnClearActionPerformed(evt);
            }
        });

        Bttn5.setText("5");
        Bttn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn5ActionPerformed(evt);
            }
        });

        bttnBagi.setText("/");
        bttnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBagiActionPerformed(evt);
            }
        });

        Bttn6.setText("6");
        Bttn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn6ActionPerformed(evt);
            }
        });

        modulus.setText("%");
        modulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TampilHasil)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Bttn1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(bttn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bttn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Bttn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bttn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bttn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(bttnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Bttn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Bttn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bttn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttnKoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(modulus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttnKurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnSamadengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnBagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TampilHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(modulus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnBagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bttn8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Bttn7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Bttn9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bttn5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bttn6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bttn1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(Bttn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bttn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnSamadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bttn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn2ActionPerformed
        angka += "2";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_Bttn2ActionPerformed

    private void Bttn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn3ActionPerformed
        angka += "3";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_Bttn3ActionPerformed

    private void bttn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn0ActionPerformed
        angka += "0";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_bttn0ActionPerformed

    private void bttnKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnKomaActionPerformed
        angka += ".";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_bttnKomaActionPerformed

    private void Bttn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn7ActionPerformed
        angka += "7";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_Bttn7ActionPerformed

    private void bttnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnKaliActionPerformed
        angka1 =Double.parseDouble(angka);
        TampilHasil.setText("x");
        angka = "";
        pilih = 3;
    }//GEN-LAST:event_bttnKaliActionPerformed

    private void Bttn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn8ActionPerformed
        angka += "8";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_Bttn8ActionPerformed

    private void bttnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnKurangActionPerformed
        angka1 =Double.parseDouble(angka);
        TampilHasil.setText("-");
        angka = "";
        pilih = 2;
    }//GEN-LAST:event_bttnKurangActionPerformed

    private void Bttn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn9ActionPerformed
        angka += "9";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_Bttn9ActionPerformed

    private void bttnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnTambahActionPerformed
        angka1 =Double.parseDouble(angka);
        TampilHasil.setText("+");
        angka = "";
        pilih = 1;
    }//GEN-LAST:event_bttnTambahActionPerformed

    private void bttn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn4ActionPerformed
        angka += "4";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_bttn4ActionPerformed

    private void bttnSamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSamadenganActionPerformed
        switch (pilih) {
            case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            TampilHasil.setText(angka);
            break;
            case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            TampilHasil.setText(angka);
            break;
            case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            TampilHasil.setText(angka);
            break;
            case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            TampilHasil.setText(angka);
            break;
            case 5:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 % angka2;
            angka = Double.toString(jumlah);
            TampilHasil.setText(angka);
            break;
            
            default:
            throw new AssertionError();
        }
    }//GEN-LAST:event_bttnSamadenganActionPerformed

    private void Bttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn1ActionPerformed
        angka += "1";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_Bttn1ActionPerformed

    private void bttnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnClearActionPerformed
        TampilHasil.setText("");
        angka1 = 0.0;
        angka2 = 0.0;
        angka = "";
    }//GEN-LAST:event_bttnClearActionPerformed

    private void Bttn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn5ActionPerformed
        angka += "5";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_Bttn5ActionPerformed

    private void bttnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBagiActionPerformed
        angka1 =Double.parseDouble(angka);
        TampilHasil.setText("/");
        angka = "";
        pilih = 4;
    }//GEN-LAST:event_bttnBagiActionPerformed

    private void Bttn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn6ActionPerformed
        angka += "6";
        TampilHasil.setText(angka);
    }//GEN-LAST:event_Bttn6ActionPerformed

    private void modulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulusActionPerformed
        angka1 = Double.parseDouble(angka);
        TampilHasil.setText("%");
        angka = "";
        pilih = 5;
    }//GEN-LAST:event_modulusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttn1;
    private javax.swing.JButton Bttn2;
    private javax.swing.JButton Bttn3;
    private javax.swing.JButton Bttn5;
    private javax.swing.JButton Bttn6;
    private javax.swing.JButton Bttn7;
    private javax.swing.JButton Bttn8;
    private javax.swing.JButton Bttn9;
    private javax.swing.JTextField TampilHasil;
    private javax.swing.JButton bttn0;
    private javax.swing.JButton bttn4;
    private javax.swing.JButton bttnBagi;
    private javax.swing.JButton bttnClear;
    private javax.swing.JButton bttnKali;
    private javax.swing.JButton bttnKoma;
    private javax.swing.JButton bttnKurang;
    private javax.swing.JButton bttnSamadengan;
    private javax.swing.JButton bttnTambah;
    private javax.swing.JButton modulus;
    // End of variables declaration//GEN-END:variables
}
